name: Test and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Using Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm test -- --coverage
      - name: Running SonarCloudScan
        uses: sonarsource/sonarcloud-github-action@master
      - name: Creating a Prod Package
        uses: actions/setup-node@v1
      - run: |
          npm run-script build
          git config --global user.email "davidggevorrgyan@gmail.com"
          git config --global user.name "davidggevorgyan"
          git remote set-url origin https://davidggevorgyan:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/davidggevorgyan/todo-react.git
          cp -r src/ dist  
          cp -r assets/ dist
          npx gh-pages -d dist
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
