name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Using Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm test -- --coverage
    - name: Running SonarCloudScan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
		CI: true

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
		run: npm run-script build
      - name: Deploy to GH Pages
        run: |
          git config --global user.email "davidggevorrgyan@gmail.com"
          git config --global user.name "davidggevorgyan"
		  git remote set-url origin https://davidggevorgyan:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/davidggevorgyan/tetris-js-flex.git
		  cp -r src/ dist
		  cp -r assets/ dist
          npx gh-pages -d dist